version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the current directory into the /app directory in the container
    depends_on:
      - rabbitmq
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=syncflow.settings
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  celery:
    build: .
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=syncflow.settings
    command: ["./wait-for-it.sh", "rabbitmq:5672", "celery", "-A", "syncflow", "worker", "--loglevel=info"]

  rabbitmq:
    image: "rabbitmq:3.8-management"
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"


